services:
    app.userbundle.services.roles:
        class: App\UserBundle\Services\RolesService
        arguments: ['%security.role_hierarchy.roles%']
    app.userbundle.services.form.group:
        class: App\UserBundle\Form\Type\GroupFormType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: app_userbundle_form_group }