<?php

namespace App\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbstractContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractContentRepository extends EntityRepository
{
}
