services:
    app.adminbundle.user.form.type:
        class: App\AdminBundle\Form\UserType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type, alias: app_adminbundle_user }
