<?php

namespace App\ECommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getLastMessageTicket($id_ticket) {
        $qb = $this->createQueryBuilder('m');
        $qb->leftJoin('m.ticket','t');
        $qb->where('t = '.$id_ticket);
        $qb->orderBy('m','ASC');
        $qb->setMaxResults(1);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getMessagesTicket($id_ticket) {
        $qb = $this->createQueryBuilder('m');
        $qb->leftJoin('m.ticket','t');
        $qb->where('t = '.$id_ticket);
        $qb->orderBy('m','ASC');
        return $qb->getQuery()->getResult();
    }

}
